site_name: Emil Oszmánbegovity
site_url: https://emilosman.com
repo_name: emilosman

theme:
  logo: assets/monogram.png
  favicon: assets/monogram.png
  name: material
  font:
    text: Georgia

extra_css:
  - /css/style.css

markdown_extensions:
  - pymdownx.tasklist
