site_name: Emil Oszmánbegovity
site_url: https://emilosman.com
repo_url: https://github.com/emilosman
repo_name: emilosman

theme:
  name: material

extra_css:
  - /css/style.css

markdown_extensions:
  - pymdownx.tasklist
