site_name: emilosman
site_url: https://emilosman.com
site_author: Emil Oszmánbegovity
site_description: >-
  Emil Oszmánbegovity | Senior Software Developer | emilosman

theme:
  logo: assets/monogram.png
  favicon: assets/monogram.png
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo

extra_css:
  - /css/style.css

markdown_extensions:
  - pymdownx.tasklist
