site_name: Emil Oszmánbegovity | Senior Software Developer | emilosman
site_url: https://emilosman.com
repo_name: emilosman

theme:
  logo: assets/monogram.png
  favicon: assets/monogram.png
  name: material

extra_css:
  - /css/style.css

markdown_extensions:
  - pymdownx.tasklist
