site_name: Emil Oszmánbegovity
site_url: https://emilosman.com
repo_url: https://github.com/emilosman/emilosman
repo_name: emilosman

theme:
  icon: assets/monogram.png
  favicon: assets/monogram.png
  name: material

extra_css:
  - /css/style.css

markdown_extensions:
  - pymdownx.tasklist
